import { SendNotificationInput } from "../types/notification";

export const sampleData: SendNotificationInput[] = [
  {
    "userId": "s1",
    "email": "sales1@company.com",
    "channel": "EMAIL",
    "groupName": "SALES",
    "topicName": "NEW_MODEL_LAUNCH",
    "readStatus": true,
    "message": "Introducing the 2025 Electric SUV! Pre-orders are now open for priority customers.",
    "priority": "HIGH",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "s1",
    "createdBy": "system"
  },
  {
    "userId": "s2",
    "email": "sales2@company.com",
    "channel": "APP",
    "groupName": "SALES",
    "topicName": "EXTENDED_WARRANTY_NOTIFICATION",
    "readStatus": true,
    "message": "Offer customers extended warranties on the latest sedan lineup this quarter.",
    "priority": "MEDIUM",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "s2",
    "createdBy": "system"
  },
  {
    "userId": "s3",
    "email": "sales3@company.com",
    "channel": "EMAIL",
    "groupName": "SALES",
    "topicName": "INSURANCE_RENEWAL_ALERT",
    "readStatus": false,
    "message": "Follow up with clients whose auto insurance policies are expiring this month.",
    "priority": "LOW",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "s3",
    "createdBy": "system"
  },

  {
    "userId": "m1",
    "email": "marketing1@company.com",
    "channel": "EMAIL",
    "groupName": "MARKETING",
    "topicName": "CUSTOMER_FEEDBACK_REQUEST",
    "readStatus": false,
    "message": "Gather post-launch feedback from customers about the new hybrid vehicle campaign.",
    "priority": "HIGH",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "m1",
    "createdBy": "system"
  },
  {
    "userId": "m2",
    "email": "marketing2@company.com",
    "channel": "APP",
    "groupName": "MARKETING",
    "topicName": "NEW_MODEL_LAUNCH",
    "readStatus": false,
    "message": "Promote the 2025 Electric SUV launch on all social media channels this week.",
    "priority": "MEDIUM",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "m2",
    "createdBy": "system"
  },
  {
    "userId": "m3",
    "email": "marketing3@company.com",
    "channel": "EMAIL",
    "groupName": "MARKETING",
    "topicName": "SERVICE_APPOINTMENT_REMINDER",
    "readStatus": true,
    "message": "Send reminders to customers for their upcoming service appointments.",
    "priority": "LOW",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "m3",
    "createdBy": "system"
  },

  {
    "userId": "sv1",
    "email": "service1@company.com",
    "channel": "APP",
    "groupName": "SERVICE",
    "topicName": "OIL_CHANGE_REMINDER",
    "readStatus": true,
    "message": "Notify customers who are due for their 6-month oil change service.",
    "priority": "HIGH",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "sv1",
    "createdBy": "system"
  },
  {
    "userId": "sv2",
    "email": "service2@company.com",
    "channel": "EMAIL",
    "groupName": "SERVICE",
    "topicName": "TIRE_PRESSURE_ALERT",
    "readStatus": true,
    "message": "Alert customers when their tire pressure monitoring system detects low levels.",
    "priority": "MEDIUM",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "sv2",
    "createdBy": "system"
  },
  {
    "userId": "sv3",
    "email": "service3@company.com",
    "channel": "APP",
    "groupName": "SERVICE",
    "topicName": "BRAKE_SYSTEM_CHECK_REQUIRED",
    "readStatus": true,
    "message": "Send a reminder for customers to check their brake system after 10,000 km.",
    "priority": "LOW",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "sv3",
    "createdBy": "system"
  },

  {
    "userId": "mf1",
    "email": "factory1@company.com",
    "channel": "EMAIL",
    "groupName": "MANUFACTURING",
    "topicName": "PRODUCTION_LINE_UPDATE",
    "readStatus": true,
    "message": "Production line 3 has achieved a record output of 500 vehicles today.",
    "priority": "HIGH",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "mf1",
    "createdBy": "system"
  },
  {
    "userId": "mf2",
    "email": "factory2@company.com",
    "channel": "APP",
    "groupName": "MANUFACTURING",
    "topicName": "PARTS_SUPPLY_DELAY",
    "readStatus": true,
    "message": "Supply chain delay reported for imported battery cells. Adjust schedules.",
    "priority": "MEDIUM",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "mf2",
    "createdBy": "system"
  },
  {
    "userId": "mf3",
    "email": "factory3@company.com",
    "channel": "EMAIL",
    "groupName": "MANUFACTURING",
    "topicName": "QUALITY_INSPECTION_REPORT",
    "readStatus": true,
    "message": "Quality inspection reports show 98% compliance across assembly lines.",
    "priority": "LOW",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "mf3",
    "createdBy": "system"
  },

  {
    "userId": "mg1",
    "email": "mgmt1@company.com",
    "channel": "APP",
    "groupName": "MANAGEMENT",
    "topicName": "SHIPMENT_TRACKING_UPDATE",
    "readStatus": true,
    "message": "New dashboard for real-time shipment tracking is now available to managers.",
    "priority": "HIGH",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "mg1",
    "createdBy": "system"
  },
  {
    "userId": "mg2",
    "email": "mgmt2@company.com",
    "channel": "EMAIL",
    "groupName": "MANAGEMENT",
    "topicName": "ENGINE_DIAGNOSTICS_ALERT",
    "readStatus": false,
    "message": "Diagnostic reports from dealerships highlight recurring engine issues.",
    "priority": "MEDIUM",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "mg2",
    "createdBy": "system"
  },
  {
    "userId": "mg3",
    "email": "mgmt3@company.com",
    "channel": "APP",
    "groupName": "MANAGEMENT",
    "topicName": "RECALL_NOTICE",
    "readStatus": true,
    "message": "Immediate recall notice issued for Model Z due to airbag safety concerns.",
    "priority": "LOW",
    "status": "NEW",
    "deepLinkUrl": "https://www.google.com",
    "viewedBy": "mg3",
    "createdBy": "system"
  }
]


